export const ACTION_TYPE = {
    LOADING_START: "LOADING_START",
    LOADING_END: "LOADING_END",
    SET_TODOS: "SET_TODOS",
    ADD_TODO: "ADD_TODO",
    EDIT_TODO: "EDIT_TODO",
    UPDATE_TODO: "UPDATE_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    SET_SEARCH_INPUT: "SET_SEARCH_INPUT",
    SET_SEARCH_PHRASE: "SET_SEARCH_PHRASE",
    SET_IS_ALPHABET_SORTING: "SET_IS_ALPHABET_SORTING",
};
